group = "com.example.app_core"
version = "1.0"

buildscript {
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath("com.android.tools.build:gradle:8.1.0")
    }
}

rootProject.allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

apply plugin: "com.android.library"

android {
    if (project.android.hasProperty("namespace")) {
        namespace = "com.example.app_core"
    }

    compileSdk = 34
    ndkVersion = android.ndkVersion

    externalNativeBuild {
        cmake {
            path = "../src/CMakeLists.txt"
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_1_8
        targetCompatibility = JavaVersion.VERSION_1_8
    }

    defaultConfig {
        minSdk = 21
    }
}

apply from: "../cargokit/gradle/plugin.gradle"

cargokit {
    manifestDir = "../rust"
    libname = "rust_core"
}